### ISSUE TITLE
How to handle HEX-STRING?

### ISSUE THREAD

**Issue by opensourcegeek** [hroi/rust-snmp#8]
Currently when I try to access HEX String output like mac addresses I just get some random characters. I think this library identifies it as Octet String,

```
running 1 test
[43, 6, 1, 4, 1, 131, 4, 11, 3, 4, 1, 1, 1, 6, 2] - OCTET STRING: \�x�P
```
 
Also the OIDs I get back in Varbinds look nothing like what's been sent - I'm no expert in SNMP so any input on that would be useful too.

**Comment by hroi** [comment]
The bytes `[43, 6, 1, 4, 1, 131, 4, 11, 3, 4, 1, 1, 1, 6, 2]`  decode to OID `1.3.6.1.4.1.388.11.3.4.1.1.1.6.2`. Was that the OID you were fetching?
It looks like you are trying to interpret the raw octet-string as utf8-data. If the octet string contains the raw mac-address, you should format them as hex yourself when printing.

**Comment by opensourcegeek** [comment]
I was just printing out responses that I get from the query, as I saw Varbinds implement Debug. Also, snmpwalk (net-snmp) somehow knows it has raw mac address (or guesses it) and interprets it, not sure how it's doing that. Do you know of a way to accommodate that in the library?

Yes that's the OID I was using. Is there some logic to decode the OID? 

Also, thanks for response.

**Comment by hroi** [comment]
Net-SNMP handles MIBs and that's how it knows how to display most data. `Display` is implemented for `ObjectIdentifier` and should print the OID in a familiar format when using `"{}"`. `OctetString` wraps `&'a [u8]`. It is your job to print the bytes as something that resembles a mac address.

**Comment by opensourcegeek** [comment]
Great thanks - both seems to work. I was using "{:?}" before, however if I use "{}" OID comes up in correct format.
